package com.example.model

data class HostStadium(
    val id: String,
    val name: String,
    val fifaName: String = "",
    val city: String,
    val country: String,
    val capacity: String,
    val latitude: Double,
    val longitude: Double,
    val fact: String,
    val image: String,
    val sport: String = "Soccer",
    val league: String = "NWSL",
    val scope: String = "USA National", // "USA National" or "International"
    val tenant: String = "",
    val surface: String = "Hybrid Grass"
)

object HostStadiumDataProvider {

    val womensHostStadiums: List<HostStadium> = listOf(
        // ==========================================
        // 🇺🇸 USA NATIONAL WOMEN'S SPORTS VENUES
        // ==========================================
        HostStadium(
            id = "STAD_CPKC",
            name = "CPKC Stadium",
            fifaName = "Kansas City Current Stadium",
            city = "Kansas City, MO",
            country = "United States",
            capacity = "11,500",
            latitude = 39.1172,
            longitude = -94.5772,
            fact = "Historic milestone: The first stadium in the world purpose-built exclusively for a women's professional sports team (Kansas City Current). Situated along the scenic Missouri River.",
            image = "https://images.unsplash.com/photo-1510563800743-aed236490d08?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "NWSL",
            scope = "USA National",
            tenant = "Kansas City Current",
            surface = "Natural Kentucky Bluegrass"
        ),
        HostStadium(
            id = "STAD_BARCLAYS",
            name = "Barclays Center",
            fifaName = "Brooklyn Arena",
            city = "Brooklyn, NY",
            country = "United States",
            capacity = "17,732",
            latitude = 40.6826,
            longitude = -73.9754,
            fact = "Home of the 2024 WNBA Champions New York Liberty (Sabrina Ionescu, Breanna Stewart). Set franchise sellout attendance records and redefined women's basketball culture.",
            image = "https://images.unsplash.com/photo-1504450758481-7338eba7524a?auto=format&fit=crop&w=800&q=80",
            sport = "Basketball",
            league = "WNBA",
            scope = "USA National",
            tenant = "New York Liberty",
            surface = "Hardwood Floor"
        ),
        HostStadium(
            id = "STAD_GAINBRIDGE",
            name = "Gainbridge Fieldhouse",
            fifaName = "Indianapolis Arena",
            city = "Indianapolis, IN",
            country = "United States",
            capacity = "17,274",
            latitude = 39.7640,
            longitude = -86.1555,
            fact = "Home of the Indiana Fever and phenomenon Caitlin Clark. Generated unprecedented television ratings and consecutive arena sellouts in modern women's sports history.",
            image = "https://images.unsplash.com/photo-1519766304817-4f37bda74a29?auto=format&fit=crop&w=800&q=80",
            sport = "Basketball",
            league = "WNBA",
            scope = "USA National",
            tenant = "Indiana Fever",
            surface = "Maple Hardwood"
        ),
        HostStadium(
            id = "STAD_MICHELOB",
            name = "Michelob ULTRA Arena",
            fifaName = "Las Vegas Arena",
            city = "Las Vegas, NV",
            country = "United States",
            capacity = "12,000",
            latitude = 36.0919,
            longitude = -115.1764,
            fact = "The fortress of the back-to-back WNBA Champions Las Vegas Aces, led by 3-time MVP A'ja Wilson and coach Becky Hammon.",
            image = "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=800&q=80",
            sport = "Basketball",
            league = "WNBA",
            scope = "USA National",
            tenant = "Las Vegas Aces",
            surface = "Hardwood"
        ),
        HostStadium(
            id = "STAD_CLIMATE",
            name = "Climate Pledge Arena",
            fifaName = "Seattle Arena",
            city = "Seattle, WA",
            country = "United States",
            capacity = "18,300",
            latitude = 47.6221,
            longitude = -122.3540,
            fact = "World's first zero-carbon certified arena and home of the 4-time WNBA Champion Seattle Storm (Jewell Loyd, Nneka Ogwumike). Powered entirely by renewable electricity.",
            image = "https://images.unsplash.com/photo-1431324155629-1a6edd1dec1d?auto=format&fit=crop&w=800&q=80",
            sport = "Basketball",
            league = "WNBA",
            scope = "USA National",
            tenant = "Seattle Storm",
            surface = "Sustainable Maple Hardwood"
        ),
        HostStadium(
            id = "STAD_TARGET_CTR",
            name = "Target Center",
            fifaName = "Minneapolis Arena",
            city = "Minneapolis, MN",
            country = "United States",
            capacity = "18,798",
            latitude = 44.9795,
            longitude = -93.2761,
            fact = "Home of the Minnesota Lynx (Napheesa Collier), 4-time WNBA Champions and Commissioner's Cup champions.",
            image = "https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&q=80",
            sport = "Basketball",
            league = "WNBA",
            scope = "USA National",
            tenant = "Minnesota Lynx",
            surface = "Hardwood"
        ),
        HostStadium(
            id = "STAD_FOOTPRINT",
            name = "Footprint Center",
            fifaName = "Phoenix Arena",
            city = "Phoenix, AZ",
            country = "United States",
            capacity = "17,071",
            latitude = 33.4457,
            longitude = -112.0712,
            fact = "Home of the Phoenix Mercury, legendary venue of Diana Taurasi and Brittney Griner, and host of the record-setting 2024 WNBA All-Star Game.",
            image = "https://images.unsplash.com/photo-1541252260730-0412e8e2108e?auto=format&fit=crop&w=800&q=80",
            sport = "Basketball",
            league = "WNBA",
            scope = "USA National",
            tenant = "Phoenix Mercury",
            surface = "Hardwood"
        ),
        HostStadium(
            id = "STAD_WINTRUST",
            name = "Wintrust Arena",
            fifaName = "Chicago Arena",
            city = "Chicago, IL",
            country = "United States",
            capacity = "10,387",
            latitude = 41.8530,
            longitude = -87.6212,
            fact = "Home of the Chicago Sky (Angel Reese, Kamilla Cardoso), 2021 WNBA Champions. Renowned for its passionate South Side fanbase.",
            image = "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=800&q=80",
            sport = "Basketball",
            league = "WNBA",
            scope = "USA National",
            tenant = "Chicago Sky",
            surface = "Hardwood"
        ),
        HostStadium(
            id = "STAD_CHASE_CTR",
            name = "Chase Center",
            fifaName = "San Francisco Arena",
            city = "San Francisco, CA",
            country = "United States",
            capacity = "18,064",
            latitude = 37.7680,
            longitude = -122.3877,
            fact = "Home of the Golden State Valkyries, the WNBA's newest expansion franchise which set record-breaking season ticket deposits before playing their first tip-off.",
            image = "https://images.unsplash.com/photo-1556486284-a15d2fef87f0?auto=format&fit=crop&w=800&q=80",
            sport = "Basketball",
            league = "WNBA",
            scope = "USA National",
            tenant = "Golden State Valkyries",
            surface = "Hardwood"
        ),
        HostStadium(
            id = "STAD_CRYPTO",
            name = "Crypto.com Arena",
            fifaName = "Los Angeles Downtown Arena",
            city = "Los Angeles, CA",
            country = "United States",
            capacity = "19,079",
            latitude = 34.0430,
            longitude = -118.2673,
            fact = "Home of the 3-time WNBA Champion Los Angeles Sparks (Cameron Brink, Rickea Jackson). Hosted Lisa Leslie's historic first dunk in WNBA history.",
            image = "https://images.unsplash.com/photo-1518063319789-7217e6706b04?auto=format&fit=crop&w=800&q=80",
            sport = "Basketball",
            league = "WNBA",
            scope = "USA National",
            tenant = "Los Angeles Sparks",
            surface = "Hardwood"
        ),
        HostStadium(
            id = "STAD_PROVIDENCE_PK",
            name = "Providence Park",
            fifaName = "Portland Stadium",
            city = "Portland, OR",
            country = "United States",
            capacity = "25,218",
            latitude = 45.5216,
            longitude = -122.6917,
            fact = "The cathedral of women's soccer in North America. Home of the 3-time NWSL Champions Portland Thorns (Sophia Smith) with the legendary Rose City Riveters supporters.",
            image = "https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "NWSL",
            scope = "USA National",
            tenant = "Portland Thorns FC",
            surface = "FieldTurf Core"
        ),
        HostStadium(
            id = "STAD_BMO_LA",
            name = "BMO Stadium",
            fifaName = "Los Angeles Stadium",
            city = "Los Angeles, CA",
            country = "United States",
            capacity = "22,000",
            latitude = 34.0128,
            longitude = -118.2849,
            fact = "Home of Angel City FC (Christen Press, Alyssa Thompson). Renowned for its groundbreaking female-led ownership and electric atmosphere in downtown Exposition Park.",
            image = "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "NWSL",
            scope = "USA National",
            tenant = "Angel City FC",
            surface = "Bermuda Grass"
        ),
        HostStadium(
            id = "STAD_AUDI_FIELD",
            name = "Audi Field",
            fifaName = "Washington DC Stadium",
            city = "Washington, DC",
            country = "United States",
            capacity = "20,000",
            latitude = 38.8687,
            longitude = -77.0128,
            fact = "Home of the 2021 NWSL Champions Washington Spirit and superstar Trinity Rodman. Located at the scenic Capitol Riverfront.",
            image = "https://images.unsplash.com/photo-1568194157720-8eae79a3761a?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "NWSL",
            scope = "USA National",
            tenant = "Washington Spirit",
            surface = "Kentucky Bluegrass"
        ),
        HostStadium(
            id = "STAD_INTERCO",
            name = "Inter&Co Stadium",
            fifaName = "Orlando Stadium",
            city = "Orlando, FL",
            country = "United States",
            capacity = "25,500",
            latitude = 28.5411,
            longitude = -81.3893,
            fact = "Home of the 2024 NWSL Shield Winners Orlando Pride, starring legendary icon Marta and Zambian phenom Barbra Banda.",
            image = "https://images.unsplash.com/photo-1577223625856-745b14c5520a?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "NWSL",
            scope = "USA National",
            tenant = "Orlando Pride",
            surface = "Latitude 36 Bermudagrass"
        ),
        HostStadium(
            id = "STAD_SNAPDRAGON",
            name = "Snapdragon Stadium",
            fifaName = "San Diego Stadium",
            city = "San Diego, CA",
            country = "United States",
            capacity = "35,000",
            latitude = 32.7844,
            longitude = -117.1224,
            fact = "Home of San Diego Wave FC (Naomi Girma). Set the all-time NWSL single-game attendance record of 32,000 fans and hosted Alex Morgan's farewell match.",
            image = "https://images.unsplash.com/photo-1516242981651-2ee338449dea?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "NWSL",
            scope = "USA National",
            tenant = "San Diego Wave FC",
            surface = "Natural Turf"
        ),
        HostStadium(
            id = "STAD_RED_BULL",
            name = "Red Bull Arena",
            fifaName = "New Jersey Stadium",
            city = "Harrison, NJ",
            country = "United States",
            capacity = "25,000",
            latitude = 40.7368,
            longitude = -74.1503,
            fact = "Home of 2023 NWSL Champions NJ/NY Gotham FC (Rose Lavelle, Lynn Williams, Esther González). A world-class soccer-specific venue.",
            image = "https://images.unsplash.com/photo-1486286701208-1d58e9338013?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "NWSL",
            scope = "USA National",
            tenant = "NJ/NY Gotham FC",
            surface = "Natural Kentucky Bluegrass"
        ),
        HostStadium(
            id = "STAD_PAYPAL_PK",
            name = "PayPal Park",
            fifaName = "San Jose Bay Stadium",
            city = "San Jose, CA",
            country = "United States",
            capacity = "18,000",
            latitude = 37.3513,
            longitude = -121.9250,
            fact = "Home of expansion sensation Bay FC (Asisat Oshoala, Racheal Kundananji). Features the largest outdoor stadium bar in North America.",
            image = "https://images.unsplash.com/photo-1524646889995-3277ab3efecf?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "NWSL",
            scope = "USA National",
            tenant = "Bay FC",
            surface = "Natural Grass"
        ),
        HostStadium(
            id = "STAD_ARTHUR_ASHE",
            name = "Arthur Ashe Stadium",
            fifaName = "US Open Center Court",
            city = "Flushing Meadows, NY",
            country = "United States",
            capacity = "23,771",
            latitude = 40.7499,
            longitude = -73.8466,
            fact = "The largest tennis stadium in the world. Host of historic US Open Women's Finals won by icons Serena Williams, Venus Williams, Naomi Osaka, and Coco Gauff.",
            image = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
            sport = "Tennis",
            league = "WTA Tour",
            scope = "USA National",
            tenant = "US Open Women's Championship",
            surface = "Laykold Hardcourt"
        ),
        HostStadium(
            id = "STAD_XCEL",
            name = "Xcel Energy Center",
            fifaName = "PWHL Minnesota Arena",
            city = "Saint Paul, MN",
            country = "United States",
            capacity = "17,954",
            latitude = 44.9448,
            longitude = -93.1011,
            fact = "Home ice of the inaugural PWHL Walter Cup Champions, the Minnesota Frost (Taylor Heise, Kendall Coyne Schofield). Setting new attendance records for women's hockey.",
            image = "https://images.unsplash.com/photo-1580748141549-71748dbe0bdc?auto=format&fit=crop&w=800&q=80",
            sport = "Ice Hockey",
            league = "PWHL",
            scope = "USA National",
            tenant = "Minnesota Frost",
            surface = "NHL Standard Ice Sheet"
        ),
        HostStadium(
            id = "STAD_TSONGAS",
            name = "Tsongas Center",
            fifaName = "PWHL Boston Arena",
            city = "Lowell / Boston, MA",
            country = "United States",
            capacity = "6,496",
            latitude = 42.6517,
            longitude = -71.3146,
            fact = "Home ice of the PWHL Boston Fleet, captained by legendary US Olympic gold medalist Hilary Knight and Megan Keller.",
            image = "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=800&q=80",
            sport = "Ice Hockey",
            league = "PWHL",
            scope = "USA National",
            tenant = "Boston Fleet",
            surface = "Ice Rink"
        ),
        HostStadium(
            id = "STAD_PRUDENTIAL",
            name = "Prudential Center",
            fifaName = "PWHL New York Arena",
            city = "Newark, NJ",
            country = "United States",
            capacity = "16,514",
            latitude = 40.7336,
            longitude = -74.1711,
            fact = "Home ice of the PWHL New York Sirens and #1 overall draft selection Sarah Fillier.",
            image = "https://images.unsplash.com/photo-1518063319789-7217e6706b04?auto=format&fit=crop&w=800&q=80",
            sport = "Ice Hockey",
            league = "PWHL",
            scope = "USA National",
            tenant = "New York Sirens",
            surface = "Ice Rink"
        ),
        HostStadium(
            id = "STAD_CHI_HEALTH",
            name = "CHI Health Center",
            fifaName = "Omaha Arena",
            city = "Omaha, NE",
            country = "United States",
            capacity = "18,320",
            latitude = 41.2625,
            longitude = -95.9288,
            fact = "The epicenter of American women's volleyball. Home of LOVB Omaha and the Omaha Supernovas, regularly drawing crowds exceeding 12,000 spectators.",
            image = "https://images.unsplash.com/photo-1511204579483-e5c2b1d69acd?auto=format&fit=crop&w=800&q=80",
            sport = "Volleyball",
            league = "LOVB / PVF",
            scope = "USA National",
            tenant = "LOVB Omaha / Supernovas",
            surface = "Taraflex Volleyball Court"
        ),
        HostStadium(
            id = "STAD_GAS_SOUTH",
            name = "Gas South Arena",
            fifaName = "Atlanta Arena",
            city = "Duluth / Atlanta, GA",
            country = "United States",
            capacity = "12,750",
            latitude = 33.9930,
            longitude = -84.0934,
            fact = "Home of the Pro Volleyball Federation (PVF) regular season champion Atlanta Vibe (Leah Edmond).",
            image = "https://images.unsplash.com/photo-1541252260730-0412e8e2108e?auto=format&fit=crop&w=800&q=80",
            sport = "Volleyball",
            league = "PVF",
            scope = "USA National",
            tenant = "Atlanta Vibe",
            surface = "Taraflex Volleyball Court"
        ),

        // ==========================================
        // 🌍 GLOBAL INTERNATIONAL WOMEN'S SPORTS VENUES
        // ==========================================
        HostStadium(
            id = "STAD_MARACANA",
            name = "Estádio do Maracanã",
            fifaName = "Rio de Janeiro Stadium",
            city = "Rio de Janeiro",
            country = "Brazil",
            capacity = "78,838",
            latitude = -22.9122,
            longitude = -43.2302,
            fact = "Chosen as the grand venue for the 2027 FIFA Women's World Cup Final! Spiritual home of football where Marta and the world's best will compete for immortality.",
            image = "https://images.unsplash.com/photo-1518063319789-7217e6706b04?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "FIFA Women's World Cup",
            scope = "International",
            tenant = "2027 FIFA WWC Final",
            surface = "Hybrid Grass"
        ),
        HostStadium(
            id = "STAD_CORINTHIANS",
            name = "Neo Química Arena",
            fifaName = "São Paulo Stadium",
            city = "São Paulo",
            country = "Brazil",
            capacity = "49,205",
            latitude = -23.5453,
            longitude = -46.4742,
            fact = "Venue for the Opening Match of the 2027 FIFA Women's World Cup. Also home of Corinthians Femenino, the dominant club power of South American women's football.",
            image = "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "FIFA Women's World Cup",
            scope = "International",
            tenant = "Corinthians Femenino",
            surface = "Hybrid Natural Grass"
        ),
        HostStadium(
            id = "STAD_NACIONAL",
            name = "Estádio Nacional Mané Garrincha",
            fifaName = "Brasília Stadium",
            city = "Brasília",
            country = "Brazil",
            capacity = "72,788",
            latitude = -15.7835,
            longitude = -47.8992,
            fact = "Architectural marvel featuring 288 monumental columns. Key semi-final host for the 2027 FIFA Women's World Cup.",
            image = "https://images.unsplash.com/photo-1486286701208-1d58e9338013?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "FIFA Women's World Cup",
            scope = "International",
            tenant = "2027 FIFA WWC",
            surface = "Natural Turf"
        ),
        HostStadium(
            id = "STAD_WEMBLEY",
            name = "Wembley Stadium",
            fifaName = "London National Stadium",
            city = "London",
            country = "United Kingdom",
            capacity = "90,000",
            latitude = 51.5560,
            longitude = -0.2796,
            fact = "Hosted the historic UEFA Women's Euro 2022 Final before an all-time tournament record crowd of 87,192 as England's Lionesses were crowned European Champions.",
            image = "https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "UEFA Women's Championship",
            scope = "International",
            tenant = "England Lionesses / Women's FA Cup Final",
            surface = "Desso GrassMaster Hybrid"
        ),
        HostStadium(
            id = "STAD_WIMBLEDON",
            name = "Centre Court, Wimbledon",
            fifaName = "All England Lawn Tennis Club",
            city = "London",
            country = "United Kingdom",
            capacity = "14,979",
            latitude = 51.4337,
            longitude = -0.2141,
            fact = "The holy grail of tennis. Cathedral where Venus and Serena Williams, Steffi Graf, Martina Navratilova, and modern WTA champions etched their names in sports lore.",
            image = "https://images.unsplash.com/photo-1510563800743-aed236490d08?auto=format&fit=crop&w=800&q=80",
            sport = "Tennis",
            league = "WTA Tour",
            scope = "International",
            tenant = "Wimbledon Ladies' Championship",
            surface = "100% Perennial Ryegrass"
        ),
        HostStadium(
            id = "STAD_ROLAND_GARROS",
            name = "Court Philippe-Chatrier",
            fifaName = "Stade Roland Garros",
            city = "Paris",
            country = "France",
            capacity = "15,225",
            latitude = 48.8471,
            longitude = 2.2498,
            fact = "The red clay throne where Iga Świątek claimed 4 French Open titles. Features a retractable roof made of 11 wings inspired by aviation hero Roland Garros.",
            image = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80",
            sport = "Tennis",
            league = "WTA Tour",
            scope = "International",
            tenant = "French Open Women's Singles",
            surface = "Red Clay"
        ),
        HostStadium(
            id = "STAD_ROD_LAVER",
            name = "Rod Laver Arena",
            fifaName = "Melbourne Park",
            city = "Melbourne",
            country = "Australia",
            capacity = "14,820",
            latitude = -37.8216,
            longitude = 144.9785,
            fact = "Epicenter of the Australian Open, where Aryna Sabalenka back-to-back captured the Daphne Akhurst Memorial Cup under the blazing Melbourne sun.",
            image = "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80",
            sport = "Tennis",
            league = "WTA Tour",
            scope = "International",
            tenant = "Australian Open Women's Championship",
            surface = "GreenSet Hardcourt"
        ),
        HostStadium(
            id = "STAD_ACCOR",
            name = "Accor Stadium",
            fifaName = "Stadium Australia",
            city = "Sydney",
            country = "Australia",
            capacity = "75,784",
            latitude = -33.8471,
            longitude = 151.0634,
            fact = "Host of the historic 2023 FIFA Women's World Cup Final where Spain defeated England 1-0 in front of 75,784 fans to lift their first world championship.",
            image = "https://images.unsplash.com/photo-1518063319789-7217e6706b04?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "FIFA Women's World Cup",
            scope = "International",
            tenant = "Australia Matildas",
            surface = "Natural Turf"
        ),
        HostStadium(
            id = "STAD_JOHAN_CRUYFF",
            name = "Camp Nou & Estadi Johan Cruyff",
            fifaName = "FC Barcelona Stadium",
            city = "Barcelona",
            country = "Spain",
            capacity = "99,354",
            latitude = 41.3809,
            longitude = 2.1228,
            fact = "Home of FC Barcelona Femení (Alexia Putellas, Aitana Bonmatí). Shattered the all-time world record for women's football attendance with 91,648 spectators in El Clásico.",
            image = "https://images.unsplash.com/photo-1568194157720-8eae79a3761a?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "UEFA Women's Champions League",
            scope = "International",
            tenant = "FC Barcelona Femení",
            surface = "Hybrid Grass"
        ),
        HostStadium(
            id = "STAD_GROUPAMA",
            name = "Groupama Stadium",
            fifaName = "Parc Olympique Lyonnais",
            city = "Lyon",
            country = "France",
            capacity = "59,186",
            latitude = 45.7653,
            longitude = 4.9819,
            fact = "Home of Olympique Lyonnais Féminin, the most successful women's football club in European history with a record 8 UEFA Champions League crowns.",
            image = "https://images.unsplash.com/photo-1577223625856-745b14c5520a?auto=format&fit=crop&w=800&q=80",
            sport = "Soccer",
            league = "UEFA Women's Champions League",
            scope = "International",
            tenant = "Olympique Lyonnais Féminin",
            surface = "AirFibr Hybrid Turf"
        ),
        HostStadium(
            id = "STAD_PLACE_BELL",
            name = "Place Bell",
            fifaName = "PWHL Montreal Arena",
            city = "Laval / Montreal",
            country = "Canada",
            capacity = "10,062",
            latitude = 45.5583,
            longitude = -73.7208,
            fact = "Home ice of PWHL Montreal Victoire, captained by 'Captain Clutch' Marie-Philip Poulin. Known for impassioned, bilingual sellout crowds singing 'Gens du Pays'.",
            image = "https://images.unsplash.com/photo-1580748141549-71748dbe0bdc?auto=format&fit=crop&w=800&q=80",
            sport = "Ice Hockey",
            league = "PWHL",
            scope = "International",
            tenant = "Montreal Victoire",
            surface = "Standard Ice Rink"
        ),
        HostStadium(
            id = "STAD_MATTAMY",
            name = "Mattamy Athletic Centre",
            fifaName = "Maple Leaf Gardens / PWHL Toronto",
            city = "Toronto",
            country = "Canada",
            capacity = "8,500",
            latitude = 43.6625,
            longitude = -79.3800,
            fact = "Historic Maple Leaf Gardens, reimagined as the home ice of the PWHL Toronto Sceptres (Sarah Nurse, Blayre Turnbull).",
            image = "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=800&q=80",
            sport = "Ice Hockey",
            league = "PWHL",
            scope = "International",
            tenant = "Toronto Sceptres",
            surface = "Ice Rink"
        ),
        HostStadium(
            id = "STAD_PALA_ALPITOUR",
            name = "Inalpi Arena (Pala Alpitour)",
            fifaName = "Turin Arena",
            city = "Turin",
            country = "Italy",
            capacity = "15,657",
            latitude = 45.0333,
            longitude = 7.6500,
            fact = "Host of the FIVB Women's Volleyball Nations League Finals and CEV Champions League Super Finals, starring Italian icon Paola Egonu.",
            image = "https://images.unsplash.com/photo-1511204579483-e5c2b1d69acd?auto=format&fit=crop&w=800&q=80",
            sport = "Volleyball",
            league = "FIVB Women's Volleyball",
            scope = "International",
            tenant = "FIVB VNL Finals",
            surface = "Taraflex Court"
        ),
        HostStadium(
            id = "STAD_ARIAKE",
            name = "Ariake Arena",
            fifaName = "Tokyo Arena",
            city = "Tokyo",
            country = "Japan",
            capacity = "15,000",
            latitude = 35.6433,
            longitude = 139.7917,
            fact = "Premier Tokyo venue for international women's volleyball and FIBA women's basketball championships, famed for its sweeping Japanese timber roof design.",
            image = "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80",
            sport = "Volleyball",
            league = "FIVB / FIBA Women",
            scope = "International",
            tenant = "Japan Women's Volleyball Team",
            surface = "Multi-Sport Hardwood / Taraflex"
        ),
        HostStadium(
            id = "STAD_MCG",
            name = "Melbourne Cricket Ground (MCG)",
            fifaName = "The 'G'",
            city = "Melbourne",
            country = "Australia",
            capacity = "100,024",
            latitude = -37.8199,
            longitude = 144.9834,
            fact = "Witnessed 86,174 spectators packing the stands for the ICC Women's T20 World Cup Final on International Women's Day, setting a global women's cricket benchmark.",
            image = "https://images.unsplash.com/photo-1541252260730-0412e8e2108e?auto=format&fit=crop&w=800&q=80",
            sport = "Cricket",
            league = "ICC Women's World Cup",
            scope = "International",
            tenant = "Australia Women's Cricket Team",
            surface = "Drop-in Cricket Pitch / Natural Turf"
        ),
        HostStadium(
            id = "STAD_DY_PATIL",
            name = "DY Patil Stadium",
            fifaName = "Navi Mumbai Stadium",
            city = "Navi Mumbai",
            country = "India",
            capacity = "45,300",
            latitude = 19.0436,
            longitude = 73.0256,
            fact = "The electric fortress of the Women's Premier League (WPL Cricket), where Smriti Mandhana and Harmanpreet Kaur play in front of 40,000+ passionate supporters.",
            image = "https://images.unsplash.com/photo-1510563800743-aed236490d08?auto=format&fit=crop&w=800&q=80",
            sport = "Cricket",
            league = "WPL (Women's Premier League)",
            scope = "International",
            tenant = "WPL Cricket Finals",
            surface = "Cricket Turf"
        )
    )

    // Backward-compatible alias: hostStadiums returns all women's sports stadiums
    val hostStadiums: List<HostStadium> get() = womensHostStadiums

    fun getStadiumsByScope(scope: String): List<HostStadium> {
        return if (scope.equals("ALL", ignoreCase = true)) womensHostStadiums
        else womensHostStadiums.filter { it.scope.equals(scope, ignoreCase = true) }
    }

    fun getStadiumsBySport(sport: String): List<HostStadium> {
        return if (sport.equals("ALL", ignoreCase = true)) womensHostStadiums
        else womensHostStadiums.filter { it.sport.equals(sport, ignoreCase = true) }
    }

    fun searchStadiums(query: String): List<HostStadium> {
        if (query.isBlank()) return womensHostStadiums
        val q = query.trim().lowercase()
        return womensHostStadiums.filter {
            it.name.lowercase().contains(q) ||
            it.city.lowercase().contains(q) ||
            it.country.lowercase().contains(q) ||
            it.tenant.lowercase().contains(q) ||
            it.sport.lowercase().contains(q) ||
            it.league.lowercase().contains(q)
        }
    }
}
